"""Write the fixed production data from the retained reference derivation."""
import pathlib
import sys
from blueprint_geometry import decode
from derive_patches import derive

source = pathlib.Path('research/cosmin1490/60.txt')
records = decode(source.read_text(encoding='utf-8'))
plan = derive(records, grid_aligned=True)
legacy = derive(records)
assert sorted(plan['positions']) == list(range(1, 61))
assert plan['source']['sha256'] == '96bd7badd6d0bd971df477b74622c0296b483e7b60e77aa3074cdf0b239620e0'

def floats(values):
    return ', '.join(format(v, '.9g') + 'f' for v in values)

def ints(values):
    return 'new[] { ' + ', '.join(map(str, values)) + ' }'

lines = [
    '// Generated by scripts/write_plan.py from Cosmin1490 reference data.',
    '// Source/terms: research/cosmin1490/README.md and research/cosmin1490/LICENSE (GPL-3.0).',
    'namespace DSPSphereBuilder', '{', '    internal static partial class SpherePlan', '    {',
    f'        public const string ReferenceSha256 = "{plan["source"]["sha256"]}";',
    '        public static readonly Position[] Directions =', '        {'
]
lines += ['            new Position(' + floats(plan['positions'][i]) + '),' for i in range(1, 61)]
lines += ['        };', '        public static readonly Position[] LegacyDirections =', '        {']
lines += ['            new Position(' + floats(legacy['positions'][i]) + '),' for i in range(1, 61)]
lines += ['        };', '        public static readonly Patch[] Patches =', '        {']
for step in plan['steps']:
    edges = ', '.join(f'new Edge({a}, {b})' for a, b in step['add_frames'])
    lines.append('            new Patch(' + ints(step['add_nodes']) + ', new[] { ' + edges + ' }),')
lines += ['        };', '        public static readonly int[][] Faces =', '        {']
lines += ['            ' + ints(face) + ',' for face in plan['faces']]
lines += ['        };', '    }', '}']
destination = pathlib.Path(sys.argv[1])
destination.parent.mkdir(parents=True, exist_ok=True)
destination.write_text('\n'.join(lines) + '\n', encoding='utf-8')
